.PHONY: help build system-up system-down restart debugger-up debugger-down logs-db clean db-only test grondonapi

# Docker compose files location
COMPOSE_FILE := infra/docker-compose.yml
COMPOSE_DEBUG_FILE := infra/docker-compose.debug.yml

# Default target
help:
	@echo "Grondona Server - Available commands:"
	@echo ""
	@echo "  make build      	- Build the Docker images"
	@echo "  make system-up     - Start all services (PostgreSQL + App)"
	@echo "  make system-down   - Stop all services"
	@echo "  make reset    	    - Restart all services and rebuild DB"
	@echo "  make clean      	- Stop services and remove volumes"
	@echo "  make db-only    	- Start only the database"
	@echo "  make shell      	- Open a shell in the app container"
	@echo "  make psql       	- Connect to PostgreSQL CLI"
	@echo "  make test       	- Run tests"
	@echo "  make build-jar  	- Build JAR file locally"
	@echo "  make debugger-up   - Start services in debug mode (port 5005)"
	@echo "  make debugger-down - Stop debug services"
	@echo "  make grondonapi 	- Generates API autogenerated models"
	@echo ""

# Build Docker images
build:
	@echo "Building Docker images..."
	docker-compose -f $(COMPOSE_FILE) build

# Start all services
system-up: build
	@echo "Starting all services..."
	docker-compose -f $(COMPOSE_FILE) up -d
	@echo ""
	@echo "Services started successfully!"
	@echo "  - API: http://localhost:8080"
	@echo "  - PostgreSQL: localhost:5432"
	@echo ""
	docker-compose -f $(COMPOSE_FILE) logs --follow app

# Stop all services
system-down:
	@echo "Stopping all services..."
	docker-compose -f $(COMPOSE_FILE) down

# Reset all services
reset: system-down clean system-up

# Start services in debug mode with JDWP enabled on port 5005
debugger-up:
	@echo "Building Docker images for debug mode..."
	docker-compose -f $(COMPOSE_FILE) -f $(COMPOSE_DEBUG_FILE) build
	@echo "Starting services in debug mode..."
	docker-compose -f $(COMPOSE_FILE) -f $(COMPOSE_DEBUG_FILE) up -d
	@echo ""
	@echo "Services started in DEBUG mode!"
	@echo "  - API: http://localhost:8080"
	@echo "  - Debug Port: localhost:5005"
	@echo "  - PostgreSQL: localhost:5432"
	@echo ""
	@echo "To attach debugger in Cursor/VS Code:"
	@echo "  1. Go to Run and Debug (Cmd+Shift+D)"
	@echo "  2. Select 'Attach to Docker Debug' configuration"
	@echo "  3. Press F5 or click the green play button"
	@echo ""
	docker-compose -f $(COMPOSE_FILE) -f $(COMPOSE_DEBUG_FILE) logs --follow

# Stop debug services
debugger-down:
	@echo "Stopping debug services..."
	docker-compose -f $(COMPOSE_FILE) -f $(COMPOSE_DEBUG_FILE) down

# View database logs
logs-db:
	docker-compose logs -f db

# Clean up everything including volumes
clean:
	@echo "Stopping services and removing volumes..."
	docker-compose -f $(COMPOSE_FILE) down -v
	@echo "Cleanup complete!"

# Start only the database (useful for local development)
db-only:
	@echo "Starting PostgreSQL..."
	docker-compose -f $(COMPOSE_FILE) up -d db
	@echo "PostgreSQL is running on localhost:5432"

# Open shell in app container
shell:
	docker-compose -f $(COMPOSE_FILE) exec app /bin/sh

# Connect to PostgreSQL CLI
psql:
	docker-compose -f $(COMPOSE_FILE) exec db psql -U grondona -d grondona

# Run tests
test:
	@echo "Running tests..."
	mvn test

# Build JAR file locally (requires Maven and JDK 17+)
build-jar:
	@echo "Building JAR file..."
	mvn clean package -DskipTests

# Run locally (requires db-only to be running)
run-local: build-jar
	@echo "Starting application locally..."
	DB_HOST=localhost DB_PORT=5432 DB_NAME=grondona DB_USER=grondona DB_PASSWORD=grondona \
	java -jar target/*.jar

APIMODELSDIR=src/main/kotlin/com/grondona/model/api

# Generate API models
grondonapi:
	@echo "Generating API models..."
	@rm -rf $(APIMODELSDIR)
	@docker run --rm \
		-v ${PWD}:/local \
		openapitools/openapi-generator-cli generate \
		-i /local/docs/openapi.yaml \
		-g kotlin-spring \
		-o /local \
		--global-property=models,modelDocs=false,modelTests=false \
		--additional-properties=modelPackage=com.grondona.model.api,serializationLibrary=jackson \
		--enable-post-process-file
