# Environment
app.env=${ENV}
spring.profile.actives=${ENV}

# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:grondona}
spring.datasource.username=${DB_USER:grondona}
spring.datasource.password=${DB_PASSWORD:grondona}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Serialization
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_empty

# JWT Configuration
jwt.secret=${JWT_SECRET:1b01ec022f04b74f469c22f93a937a61b020c0945cb981df5f2fc1f7d59d4cba}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Error logging
logging.level.com.grondona=DEBUG
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# Matches API
external.api.matches.with-new-matches=false
external.api.matches.with-updated-quotas=false
external.api.matches.poll-interval-ms=10000
external.api.matches.base-url=http://mocknaldo:8085
external.api.matches.timeout-ms=3000
external.api.matches.key=key
external.api.matches.secret=secret